"""Bake the pinned Inter font into a portable, antialiased SDL alpha atlas.

Development-only dependency: Pillow 12.3.0. Normal builds use the checked-in
result and need neither Python imaging libraries nor system fonts.
"""
from hashlib import sha256
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "third_party/Inter/InterVariable.ttf"
assert sha256(SOURCE.read_bytes()).hexdigest() == "4989b125924991b90d05b2d16e0e388c48f7d5bb8b30539bbf9c755278d0ccaf"
SIZE, WIDTH = 64, 1024
characters = sorted(set(range(32, 127)) | set(range(160, 256)) |
                    {0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2026,
                     0x2190, 0x2191, 0x2192, 0x2193, 0x2212, 0x2318})
image = Image.new("L", (WIDTH, 4096))
draw = ImageDraw.Draw(image)
x, y, row_height = 2, 2, 0
records = []
for weight in (400, 600):
    font = ImageFont.truetype(str(SOURCE), SIZE)
    font.set_variation_by_axes([14, weight])
    for code in characters:
        char = chr(code)
        left, top, right, bottom = font.getbbox(char, anchor="ls")
        width, height = right - left, bottom - top
        if x + width + 2 > WIDTH:
            x, y, row_height = 2, y + row_height + 4, 0
        draw.text((x - left, y - top), char, font=font, anchor="ls", fill=255)
        records.append((code, weight, x, y, width, height, left, top, font.getlength(char)))
        x += width + 4
        row_height = max(row_height, height)
height = y + row_height + 2
assert height <= image.height
pixels = image.crop((0, 0, WIDTH, height)).tobytes()
encoded = []
for alpha in pixels:
    if encoded and encoded[-1] == alpha and encoded[-2] < 255:
        encoded[-2] += 1
    else:
        encoded.extend((1, alpha))
lines = ["// Generated by tools/bake_ui_font.py. Inter 4.1; see third_party/Inter/LICENSE.txt.",
         f"constexpr int atlas_width = {WIDTH}, atlas_height = {height};",
         "constexpr float atlas_size = 64.0F;",
         "constexpr Glyph glyphs[]{"]
for code, weight, gx, gy, gw, gh, left, top, advance in records:
    lines.append(f"    {{{code}, {weight}, {gx}, {gy}, {gw}, {gh}, {left}, {top}, {advance:.6f}F}},")
lines += ["};", "constexpr unsigned char atlas_runs[]{"]
for start in range(0, len(encoded), 32):
    lines.append("    " + ",".join(map(str, encoded[start:start + 32])) + ",")
lines += ["};", ""]
(ROOT / "src/app/font_atlas.inc").write_text("\n".join(lines), encoding="utf-8")
print(f"Baked {len(records)} glyphs into {WIDTH} x {height}; {len(encoded)} encoded bytes")
