"""Rebuild embedded circuit artwork. Maintainer dependencies: CairoSVG and Pillow."""
from io import BytesIO
from pathlib import Path
from xml.etree import ElementTree

import cairosvg
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('wire', 'crossing', 'source', 'signal', 'and', 'or', 'nand', 'nor',
         'relay-open', 'relay-closed', 'screen', 'file-input', 'file-output')
SIZE = 512


def main():
    atlas = Image.new('L', (SIZE * 4, SIZE * 4))
    for i, name in enumerate(NAMES):
        svg = (ROOT / 'assets/components' / (name + '.svg')).read_bytes()
        root = ElementTree.fromstring(svg)
        width = float(root.attrib['viewBox'].split()[2])
        for node in root.iter():
            if 'stroke-width' in node.attrib:
                node.set('stroke-width', str(width * .045))
        rendered = cairosvg.svg2png(bytestring=ElementTree.tostring(root), output_width=1024, output_height=1024)
        alpha = Image.open(BytesIO(rendered)).convert('RGBA').getchannel('A')
        bounds = alpha.getbbox()
        if bounds is None:
            raise ValueError('Empty component artwork: ' + name)
        alpha = alpha.crop(bounds)
        alpha.thumbnail((SIZE - 16, SIZE - 16), Image.Resampling.LANCZOS)
        atlas.paste(alpha, (i % 4 * SIZE + (SIZE - alpha.width) // 2,
                            i // 4 * SIZE + (SIZE - alpha.height) // 2))
    # Each pair is a 16-bit count and 8-bit alpha, stored in one 32-bit value.
    runs = []
    previous, count = None, 0
    for alpha in atlas.tobytes():
        if alpha != previous or count == 65535:
            if count:
                runs.append((count << 8) | previous)
            previous, count = alpha, 1
        else:
            count += 1
    runs.append((count << 8) | previous)
    rows = [', '.join(str(v) for v in runs[i:i + 16]) for i in range(0, len(runs), 16)]
    output = '// Generated by tools/build_symbol_atlas.py; source SVGs and notices in assets/components.\n'
    output += 'constexpr int symbol_tile_size = 512, symbol_atlas_size = 2048;\n'
    output += 'constexpr std::uint32_t symbol_runs[]{\n    ' + ',\n    '.join(rows) + '\n};\n'
    (ROOT / 'src/app/symbol_atlas.inc').write_text(output)
    preview = Image.new('RGB', (1000, 780), '#f5f8fa')
    draw = ImageDraw.Draw(preview)
    for i, name in enumerate(NAMES):
        x, y = i % 4 * 250, i // 4 * 195
        crop = atlas.crop((i % 4 * SIZE, i // 4 * SIZE, (i % 4 + 1) * SIZE, (i // 4 + 1) * SIZE))
        crop.thumbnail((150, 150), Image.Resampling.LANCZOS)
        preview.paste('#20303c', (x + 50, y + 15, x + 200, y + 165), crop)
        draw.text((x + 65, y + 170), name, fill='#20303c')
    (ROOT / 'build/symbol-research').mkdir(parents=True, exist_ok=True)
    preview.save(ROOT / 'build/symbol-research/contact-sheet.png')
    print(f'Embedded {len(NAMES)} images in {len(runs)} runs')


if __name__ == '__main__':
    main()
