include(GNUInstallDirs)

install(TARGETS gatehaven-cli RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
if(GATEHAVEN_BUILD_APP)
    install(TARGETS gatehaven BUNDLE DESTINATION . RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
    if(APPLE)
        install(DIRECTORY docs samples third_party DESTINATION gatehaven.app/Contents/Resources)
        install(FILES README.md LICENSE DESTINATION gatehaven.app/Contents/Resources)
    elseif(UNIX)
        install(FILES packaging/linux/com.michaelbaffourawuah.gatehaven.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
        install(FILES packaging/linux/gatehaven.xml DESTINATION ${CMAKE_INSTALL_DATADIR}/mime/packages)
        install(FILES packaging/gatehaven.svg DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/scalable/apps)
    endif()
endif()
install(FILES README.md LICENSE DESTINATION ${CMAKE_INSTALL_DATADIR}/gatehaven)
install(DIRECTORY docs samples third_party DESTINATION ${CMAKE_INSTALL_DATADIR}/gatehaven)
install(FILES tools/acceptance.py tools/acceptance.html DESTINATION ${CMAKE_INSTALL_DATADIR}/gatehaven/acceptance)
if(APPLE AND GATEHAVEN_BUILD_APP)
    install(FILES tools/acceptance.py tools/acceptance.html DESTINATION gatehaven.app/Contents/Resources/acceptance)
endif()

# Include the redistributable Microsoft runtime when built with MSVC.
set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION ${CMAKE_INSTALL_BINDIR})
include(InstallRequiredSystemLibraries)

configure_file(packaging/build-metadata.json.in build-metadata.json @ONLY)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/build-metadata.json" DESTINATION ${CMAKE_INSTALL_DATADIR}/gatehaven)
if(APPLE AND GATEHAVEN_BUILD_APP)
    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/build-metadata.json" DESTINATION gatehaven.app/Contents/Resources)
endif()
