# Portable archives use static SDL; ordinary SDK-based installs may use shared SDL.
if(GATEHAVEN_BUILD_APP)
    get_target_property(GATEHAVEN_SDL_TYPE SDL3::SDL3 TYPE)
    if(NOT GATEHAVEN_SDL_TYPE STREQUAL "STATIC_LIBRARY")
        message(FATAL_ERROR "Portable packages require static SDL3. Build SDL with SDL_SHARED=OFF and SDL_STATIC=ON.")
    endif()
endif()
set(CPACK_PACKAGE_NAME Gatehaven)
set(CPACK_PACKAGE_VENDOR "Michael Baffour Awuah")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A native digital logic sandbox")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_FILE_NAME "Gatehaven-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_CHECKSUM SHA256)
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY ON)
if(WIN32 OR APPLE)
    set(CPACK_GENERATOR ZIP)
else()
    set(CPACK_GENERATOR TGZ)
endif()
include(CPack)
