# Portable archives use static SDL; ordinary SDK-based installs may use shared SDL.
if(GATEHAVEN_BUILD_APP)
    get_target_property(GATEHAVEN_SDL_TYPE SDL3::SDL3 TYPE)
    if(NOT GATEHAVEN_SDL_TYPE STREQUAL "STATIC_LIBRARY")
        message(FATAL_ERROR "Portable packages require static SDL3. Build SDL with SDL_SHARED=OFF and SDL_STATIC=ON.")
    endif()
endif()
set(CPACK_PACKAGE_NAME Gatehaven)
set(CPACK_PACKAGE_VENDOR "Michael Baffour Awuah")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A native digital logic sandbox")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_FILE_NAME "Gatehaven-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_CHECKSUM SHA256)
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY ON)
if(WIN32 OR APPLE)
    set(CPACK_GENERATOR ZIP)
else()
    set(CPACK_GENERATOR TGZ)
endif()
if(GATEHAVEN_BUILD_INSTALLERS)
    if(APPLE)
        list(APPEND CPACK_GENERATOR DragNDrop)
        set(CPACK_DMG_VOLUME_NAME "Gatehaven ${PROJECT_VERSION}")
    elseif(UNIX)
        list(APPEND CPACK_GENERATOR DEB)
        set(CPACK_DEBIAN_PACKAGE_NAME gatehaven)
        set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Michael Baffour Awuah")
        set(CPACK_DEBIAN_PACKAGE_SECTION education)
        set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
        set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    else()
        message(FATAL_ERROR "Preview installers currently support Linux DEB and macOS DMG")
    endif()
endif()
set(CPACK_PROJECT_CONFIG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/package_generator.cmake")
include(CPack)
